version: '3.8'
services:
  postgres:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      POSTGRES_USER: marketplace_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marketplace_db
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: marketplace_user
      DB_PASSWORD: password
      DB_NAME: marketplace_db
      JWT_SECRET: jwt_secret
volumes:
  pgdata:
